-- 创建 JD 匹配分析表（简历与岗位JD匹配度检测）
CREATE TABLE jd_match_analyses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resume_id BIGINT NOT NULL,
  resume_filename VARCHAR(255) NOT NULL,
  jd_title VARCHAR(255),
  jd_text TEXT NOT NULL,
  overall_score INTEGER,
  hard_requirement_score INTEGER,
  skill_match_score INTEGER,
  experience_score INTEGER,
  project_score INTEGER,
  soft_skill_score INTEGER,
  summary TEXT,
  jd_requirements_json TEXT,
  strengths_json TEXT,
  gaps_json TEXT,
  suggestions_json TEXT,
  interview_questions_json TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  error VARCHAR(500),
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  CONSTRAINT jd_match_analyses_status_check
    CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_jd_match_resume_id ON jd_match_analyses (resume_id);
CREATE INDEX idx_jd_match_created_at ON jd_match_analyses (created_at DESC);
